### ISSUE TITLE
curl missing from auto-build firmware

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#150]
The curl package isn't installed on the mynet n600 image I got from https://builds.sudomesh.org/sudowrt-firmware/latest/

This makes autoconf not working.

**Comment by Juul** [comment]
@paidforby any ideas?

**Comment by eenblam** [comment]
Oh, weird! I noticed this in my own builds - see #145. I didn't realize it wasn't just mine, so I thought my builds were broken somehow.

**Comment by paidforby** [comment]
weird, curl is definitely listed in [packages](https://github.com/sudomesh/sudowrt-firmware/blob/master/openwrt_config/packages). i would start by running the rebuild locally with debugging enabled by adding `V=s` option to make in this line in build_lib, https://github.com/sudomesh/sudowrt-firmware/blob/master/build_lib#L346 and check what happens when it tries to install curl. Maybe something changed with the curl package for openwrt? I don't have an N600 on hand to test with, can try reproducing later this week.

**Comment by paidforby** [comment]
few things I notice after running a fresh build (not a rebuild),
1. We are installing both `libcurl` and `curl`. Wonder if there's conflict? Or what's the difference?
2. The `curl` is found in 2 or 3 locations,
`feeds/oldpackages/package/network/utils/curl`
`feeds/openwrt/lang/perl-www-curl`
`feeds/wlanslovenija/net/curl`
What's the difference? Which, if any, are getting installed?
3. Is this just an issue when "rebuilding" or is it an issue on first build also?

**Comment by paidforby** [comment]
Notes regarding test builds I ran today,

* fresh build of firmware in a new docker container, resulting binary does have `curl` installed.
* create a new container from the image generated by the fresh build, re-run make using `build_only` as entrypoiny, which calls `openwrt_rebuilder` function from `build_lib`, new binary does not have `curl` installed.
* create a new container from the image generated by the fresh build, re-run make using `build_pre` as entrypoint, which reruns the full build in the same way as a fresh builds, new binary does have curl installed! The build still only took a few minutes to complete, just like the rebuilder.

This third attempt appears to be the solution, I'm guessing the rebuilder function was missing some crucial configurations that prevented some packages from being installed.
