### ISSUE TITLE
Support TP-Link N600/N750 as extender nodes

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#32]
If someone has a big house or apartment complex and don't mind either running ethernet cable or using ethernet over power cable solutions, then this would be really nice. It's definitely something people will ask for.

**Comment by paidforby** [comment]
It is possible to run wire between two home nodes and mesh over their extender node ports, which is what this issue seems to suggest, so I'm guessing this was solved at some point in the last three years. Furthermore. extender node firmware is no longer maintained, see https://github.com/sudomesh/sudowrt-firmware/issues/38#issuecomment-428401179 for more on that
