### ISSUE TITLE
Allow extender nodes to be connected in series

### ISSUE THREAD

**Issue by Juul** [sudomesh/sudowrt-firmware#33]
It would be pretty cool if you could string extender nodes together in series (for extender nodes with multiple ports). Each extender node would use the wan port to hook into the home node, then two LAN ports would be for extending and the other two for open and or private networks. The open network is just on VLAN 10 so that's just a matter of enabling VLAN 10 on both the LAN port and the extender ports and bridging them together with the peoplesopen.net wifi network. For the adhoc they'd simply use VLAN 1 for LAN port 1 and VLAN 2 for LAN port 2 just like the home nodes (this won't conflict since there is no bridging for the adhoc) and then add those interfaces to babeld.

The biggest problems are:
- The extender node would have to run notdhcpserver
- The extender node would need to have IPs from the /26 to hand out to its clients

One way to do this would be extending notdhcp to support clients requesting multiple IPs from the server and having more than 4 IPs per /26 dedicated to extender nodes. This has the problem that it only works for the first two serially connected extender nodes. If an extender node is twice-removed from the home node then it won't work.

**Comment by paidforby** [comment]
Gonna close this as outdated, since we are no longer maintaining extender node firmware. This kind of setup can be accomplished with airOS and we should document it once we actually deploy it. Additionally, If someone picks the extender node firmware back up, they should explore this setup and open a new issue when they run in to a problem.
