### ISSUE TITLE
led stops working after running makenode

### ISSUE THREAD

**Issue by miloh** [sudomesh/sudowrt-firmware#99]
updated firmware from builds.sudomesh.org on aug 02 2016, after running makenode (c648e084) on my debian jesse system, the router leds stopped lighting up. They look like they work because they light up after rebooting.

**Comment by bennlich** [comment]
After some poking around w/ @paidforby, I think this might because of LED config missing from [/etc/config/system](https://github.com/sudomesh/sudowrt-firmware/blob/master/files/etc/config/system). I'll look at the config of a factory default router and see if we're missing some sensical defaults.

**Comment by paidforby** [comment]
Zeroconf branch addresses this issue. Otherwise this is a problem with makenode, not sudowrt. If y'all would still like support for leds after running makenode, please open an issue in the makenode repo, or manually add the led configs shown in this file [zeroconf:/files/etc/config/system](https://github.com/sudomesh/sudowrt-firmware/blob/823bc5118e84e9968e0004d4347f5dce760cb094/files/etc/config/system) to `/etc/config/system` on your node.

**Comment by bennlich** [comment]
Woot! Awesome.
